dist: jammy
language: c
env:
- PG_MAJOR=16
- PG_MAJOR=15
- PG_MAJOR=14
- PG_MAJOR=13
- PG_MAJOR=12
- PG_MAJOR=11
before_script:
- curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
- echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update
- sudo systemctl stop postgresql
- sudo apt-get install -y --no-install-recommends postgresql-client-${PG_MAJOR} postgresql-${PG_MAJOR} postgresql-server-dev-${PG_MAJOR}
- sudo systemctl stop postgresql
script: ./run-tests.sh
after_script:
- cat regression.diffs
- cat logfile
